# Cartesia.AI Configuration for BrendaCore
# Voice-enabled PM agent configuration

cartesia:
  # API Configuration
  api:
    api_key: ${CARTESIA_API_KEY}
    webhook_secret: ${CARTESIA_WEBHOOK_SECRET}
    base_url: "https://api.cartesia.ai/v1"
    timeout: 30
    max_retries: 3
    
  # Line Agent Configuration
  line_agent:
    agent_name: "Brenda-PM"
    agent_id: "brenda-pm-001"
    phone_number: ${CARTESIA_PHONE_NUMBER}
    backup_number: ${CARTESIA_BACKUP_NUMBER}
    
    # Voice Configuration
    voice:
      model: "sassy-professional-female"
      language: "en-US"
      accent: "neutral"
      age: "adult"
      gender: "female"
      
    # Authentication Settings
    authentication:
      enabled: true
      method: "voice_biometric"
      require_for_escalations: false
      max_attempts: 3
      timeout_seconds: 30
      
    # Webhook Configuration
    webhook:
      endpoint: "/webhooks/cartesia"
      public_url: ${WEBHOOK_PUBLIC_URL}
      verify_signature: true
      retry_failed_events: true
      max_event_age_seconds: 300
      
  # Voice Settings
  voice_settings:
    # Base Parameters
    base:
      speed: 1.0
      pitch: 1.0
      volume: 1.0
      clarity: 0.9
      
    # Sass Modulation
    sass_modulation:
      enabled: true
      speed_multiplier: 0.05
      pitch_variance: 0.1
      max_speed: 1.5
      min_speed: 0.8
      
    # Emotion Mapping
    emotions:
      neutral:
        speed: 1.0
        pitch: 1.0
        emphasis: 0.5
      frustrated:
        speed: 1.1
        pitch: 1.05
        emphasis: 0.7
      sarcastic:
        speed: 0.95
        pitch: 1.02
        emphasis: 0.8
      urgent:
        speed: 1.2
        pitch: 1.1
        emphasis: 0.9
      crisis:
        speed: 1.3
        pitch: 1.15
        emphasis: 1.0
        
    # Interruption Handling
    interruption:
      enabled: true
      base_threshold: 0.5
      sass_adjustment: -0.05
      min_threshold: 0.1
      patience_timeout: 3.0
      
  # Call Management
  call_management:
    # Inbound Settings
    inbound:
      auto_answer: true
      greeting_delay_ms: 500
      authentication_required: true
      record_calls: false
      max_duration_minutes: 30
      
    # Outbound Settings
    outbound:
      enabled: true
      max_ring_time_seconds: 30
      retry_on_busy: true
      max_retries: 2
      retry_delay_seconds: 60
      voicemail_detection: true
      
    # Escalation Settings
    escalation:
      enabled: true
      priority_levels:
        - name: "low"
          ring_time: 30
          retry_count: 1
        - name: "medium"
          ring_time: 45
          retry_count: 2
        - name: "high"
          ring_time: 60
          retry_count: 3
        - name: "critical"
          ring_time: 90
          retry_count: 5
          backup_numbers: true
          
    # Transfer Settings
    transfer:
      enabled: true
      targets:
        human_operator: ${HUMAN_OPERATOR_NUMBER}
        technical_support: ${TECH_SUPPORT_NUMBER}
        management: ${MANAGEMENT_NUMBER}
      announcement_before_transfer: true
      
  # Speech Recognition
  speech_recognition:
    model: "enhanced"
    language: "en-US"
    profanity_filter: false
    punctuation: true
    word_timestamps: false
    confidence_threshold: 0.7
    interim_results: true
    max_alternatives: 1
    
  # Text-to-Speech
  text_to_speech:
    model: "neural"
    voice_id: "brenda-sassy"
    audio_format: "mp3"
    sample_rate: 24000
    bitrate: 128
    
    # SSML Support
    ssml:
      enabled: true
      emphasis_tags: true
      pause_tags: true
      pitch_tags: true
      rate_tags: true
      
  # Analytics & Monitoring
  analytics:
    enabled: true
    track_sentiment: true
    track_interruptions: true
    track_sass_effectiveness: true
    
    # Metrics Collection
    metrics:
      - call_duration
      - authentication_success_rate
      - escalation_rate
      - sass_level_distribution
      - emotion_detection_accuracy
      - speech_recognition_confidence
      
    # Reporting
    reporting:
      daily_summary: true
      weekly_dashboard: true
      alert_on_failures: true
      
  # Security
  security:
    # Encryption
    encrypt_recordings: true
    encrypt_transcripts: true
    encryption_key: ${ENCRYPTION_KEY}
    
    # Data Retention
    retention:
      recordings_days: 30
      transcripts_days: 90
      metrics_days: 365
      
    # Access Control
    access:
      require_api_key: true
      ip_whitelist: []
      rate_limiting:
        enabled: true
        requests_per_minute: 60
        requests_per_hour: 1000
        
  # Development & Testing
  development:
    sandbox_mode: ${CARTESIA_SANDBOX_MODE:false}
    test_phone_number: ${TEST_PHONE_NUMBER}
    debug_logging: ${DEBUG_MODE:false}
    mock_responses: false
    
    # Test Voices
    test_voices:
      - id: "test-patient"
        sass_level: 1
      - id: "test-normal"
        sass_level: 5
      - id: "test-sarcastic"
        sass_level: 8
      - id: "test-crisis"
        sass_level: 11
        
# Environment-specific Overrides
environments:
  development:
    cartesia:
      development:
        sandbox_mode: true
        debug_logging: true
        mock_responses: true
        
  staging:
    cartesia:
      api:
        base_url: "https://staging-api.cartesia.ai/v1"
      development:
        sandbox_mode: true
        debug_logging: true
        
  production:
    cartesia:
      development:
        sandbox_mode: false
        debug_logging: false
      security:
        access:
          ip_whitelist:
            - ${PRODUCTION_IP_1}
            - ${PRODUCTION_IP_2}